Rush-02: main.c parsing.c strutils.c check.c file_manager.c dictionnary_manager.c writing_number.c
	@gcc -o Rush-02 main.c parsing.c strutils.c check.c file_manager.c dictionnary_manager.c writing_number.c -g -Wall -Werror -Wextra -I.

fclean:
	@rm -rf Rush-02
