Rush-02: main.c parsing.c strutils.c check.c file_manager.c dictionnary_manager.c
	gcc -o Rush-02 main.c parsing.c strutils.c check.c file_manager.c dictionnary_manager.c -g -I.

fclean:
	@rm -rf Rush-02
